apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
spec:
  selector:
    matchLabels:
      app: investment-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
      - image: fragg90/investment-service:1.2.1
        name: investment-service
        env:
        - name: spring.datasource.url
          valueFrom:
            configMapKeyRef:
              name: finance-manager-configmap
              key: datasource.investment
        - name: spring.datasource.username
          valueFrom:
            configMapKeyRef:
              name: finance-manager-configmap
              key: db.user
        - name: spring.datasource.password
          valueFrom:
            configMapKeyRef:
              name: finance-manager-configmap
              key: db.password
        - name: eureka.client.serviceUrl.defaultZone
          valueFrom:
            configMapKeyRef:
              name: finance-manager-configmap
              key: eureka.serviceUrl
        - name: eureka.instance.prefer-ip-address
          value: "true"
        ports:
        - containerPort: 8065
          name: inv-service
---
apiVersion: v1
kind: Service
metadata:
  name: invservice
spec:
  type: NodePort
  ports:
  - port: 3307
    nodePort: 30005
    targetPort: 30005
  selector:
    app: investment-service